### PR TITLE
[Bug] Update protocols pulser syntax

### LINKED ISSUE #34: [Bug] Fix ZNE for new Pulser syntax
Update ZNE functionality to new Pulser syntax and new Qadence feature for computing expectation values for noisy simulations.

### PR DESCRIPTION
**Pull request by RolandMacDoland**
Closes #34

### CODE REVIEW

**Comment by RolandMacDoland** [comment]
Hey @rajaiitp this will fail because it needs unreleased features in Qadence. Nevertheless, if you could have a look in the meantime.

**Comment by rajaiitp** [comment]
Looks good to me, would be nice to have a minimal test case run directly via pulser exclusively and match it with the output from qadence calls, just to ensure conventions, endianess are not messed up.  If there is one already, probably can ignore this.

Maybe the result from pulser can be hard coded idk

**Comment by RolandMacDoland** [comment]
Hey @rajaiitp the new Qadence release fixes it. Can you please review and approve if so ?

**Review by rajaiitp — APPROVED** [review]
lgtm. Thanks for the changes !

**Pull request merged**
