### PR TITLE
[Refactor] Imports from main namespace and API changes.

### LINKED ISSUE #17: [Infra] Enable imports from the main namespace

### PR DESCRIPTION
**Pull request by RolandMacDoland**
Closes #17 .

- [x] Import `Mitigation` from main namespace
- [x] Turn `.mitigation` method into `__call__`

### CODE REVIEW

**Comment by RolandMacDoland** [comment]
@chMoussa Just FYI, your `qadence_measurements` can also be developed here. This would avoid multiply and maintain too many repos.

**Comment by chMoussa** [comment]
@Roland-djee I think the docs should be adapted as well, no?

**Comment by RolandMacDoland** [comment]
> @Roland-djee I think the docs should be adapted as well, no?

Well, indeed. I would suggest to make the protocol class quite generic and subclass it for various specific ones: for mitigations, measurements etc. If that make sense.

**Comment by chMoussa** [comment]
> > @Roland-djee I think the docs should be adapted as well, no?
> 
> Well, indeed. I would suggest to make the protocol class quite generic and subclass it for various specific ones: for mitigations, measurements etc. If that make sense.

Another MR?

**Comment by RolandMacDoland** [comment]
> > > @Roland-djee I think the docs should be adapted as well, no?
> > 
> > 
> > Well, indeed. I would suggest to make the protocol class quite generic and subclass it for various specific ones: for mitigations, measurements etc. If that make sense.
> 
> Another MR?

Ah indeed. I didn't mean to add it here.

**Comment by chMoussa** [comment]
I am just taking it from here @Roland-djee

**Comment by RolandMacDoland** [comment]
> I am just taking it from here @Roland-djee

Cool. I think this PR can be merged if that's OK with you and you can take over from `main`.

**Review by chMoussa — APPROVED** [review]

**Pull request merged**
